language: r
r:
  - devel
  - bioc-devel
  
cache: packages
bioc_required: true

os:
  - linux
  - osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"

branches:
  only:
    - master
