# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
exclude: ['README.md', 'TODO.md', 'LICENSE']

# Setup
title: PopSV
email: jean.monlong@mail.mcgill.ca
description: > 
  Population-based Detection of Copy-Number Variation from High-Througput Sequencing.
baseurl: "/PopSV/"
tagline:          'Population-based CNV detection'

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jmonlong/PopSV
